"""
tools/update_readme.py

Utility script to update the README.md with Python version support badges.
Scans the artifacts directory for 'python_version_*.txt' success markers
generated by the CI pipeline and generates a badge for each supported version.

Usage:
    python tools/update_readme.py <artifacts_dir>
"""

import os
import re
import sys


def main():
    """
    Main execution function.
    Reads artifacts, generates badges, and updates the README file.
    """
    if len(sys.argv) < 2:
        print("Usage: python update_readme.py <artifacts_dir>")
        sys.exit(1)

    artifacts_dir = sys.argv[1]
    readme_path = "README.md"

    try:
        # 1. Identify Supported Versions
        supported_versions = []

        if not os.path.exists(artifacts_dir):
            print(f"Error: Artifacts directory '{artifacts_dir}' not found.")
            sys.exit(1)

        # List artifacts directory to find success markers
        for file in os.listdir(artifacts_dir):
            if file.startswith("python_version_") and file.endswith(".txt"):
                # Extract version number from filename: python_version_3.12.txt -> 3.12
                version = file.replace("python_version_", "").replace(".txt", "")
                supported_versions.append(version)

        # Helper to parse version string safely
        def parse_version(v):
            try:
                return tuple(map(int, v.split(".")))
            except ValueError:
                return None

        # Dedup, filter, and sort valid versions
        unique_versions = set(supported_versions)
        valid_versions = []
        for v in unique_versions:
            if parse_version(v) is not None:
                valid_versions.append(v)
            else:
                print(f"Warning: Malformed version string '{v}', skipping.")

        # Numeric Sort (3.10 > 3.9)
        valid_versions.sort(key=parse_version)

        if not valid_versions:
            print("No supported versions found in artifacts.")
            sys.exit(1)

        print(f"Found supported versions: {valid_versions}")

        # 2. Generate Badge Markdown
        # Uses img.shields.io for badges
        badges = []
        for v in valid_versions:
            badge = f"![Python {v}](https://img.shields.io/badge/python-{v}-blue?logo=python&logoColor=white)"
            badges.append(badge)

        badges_md = " ".join(badges)

        # 3. Update README
        if not os.path.exists(readme_path):
            print(f"Error: {readme_path} not found.")
            sys.exit(1)

        with open(readme_path, "r", encoding="utf-8") as f:
            content = f.read()

        # Regex to find and replace the existing badge section
        # Captures start marker, content, and end marker
        pattern = r"(<!-- BADGES_START -->)(.*?)(<!-- BADGES_END -->)"

        match = re.search(pattern, content, re.DOTALL)
        if match:
            new_content = re.sub(pattern, f"\\1\n{badges_md}\n\\3", content, flags=re.DOTALL)

            with open(readme_path, "w", encoding="utf-8") as f:
                f.write(new_content)
            print("README.md updated successfully with badges.")
        else:
            print("Error: Badge markers not found in README.md")
            print("--- Debug: README Start ---")
            print(content[:500])
            print("--- Debug: README End ---")
            sys.exit(1)

    except Exception as e:
        print(f"Error updating README: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
